### ISSUE TITLE
Settings do not save

### ISSUE THREAD

**Issue by J-Lowrance** [libvibrant/vibrantLinux#43]
No settings made are changed on session exit

When logging back in, the list of programs is empty, color setting, and the option for run on startup is not remembered or respected.

Running flatpak version on Ubuntu 22.04

**Comment by Scrumplex** [comment]
Can you make sure you are running the latest version? (Should be 2.1.10).

There have been similar issues like #41 #38

**Comment by J-Lowrance** [comment]
I am on 2.1.10.

**Comment by Scrumplex** [comment]
Can you run the program in a terminal, make some changes and send the output here

**Comment by dull4h4n** [comment]
This has long been an issue for me as well. When I run the app in terminal via vibrantlinux, nothing shows in terminal when I make a change.

Specifically I just want systemwide 115 on both displays because I'm pretty colorblind and it helps me distinguish color. When I restart my system, vibrantlinux starts but it has returned to 100 baseline.

I have also tried setting it to plasmashell specifically, but that setting is also gone after a restart.

**Comment by dull4h4n** [comment]
Another thing to note. When I set it to 115 systemwide and exit and restart the app (without restarting computer), the 115 drops to 114.

**Comment by Tiagoquix** [comment]
@Scrumplex Same issue as #57?
