### ISSUE TITLE
AUR package found

### ISSUE THREAD

**Issue by TheEvilSkeleton** [libvibrant/vibrantLinux#8]
Hello, I have found an AUR package in case you want to add it to the README: https://aur.archlinux.org/packages/vibrantlinux-git/

**Comment by zee-mzha** [comment]
thanks for the tip, I've already come across this (I actually use it instead of installing it on my own :p) but I've decided not to maintain distro specific install instructions. If you or anyone else has any objections to this please feel free to tell me about it, I'm open to reconsidering. I'll leave this issue open for anyone who wants to give their opinion on the topic.

**Comment by zee-mzha** [comment]
ayy lmao hit the wrong button

**Comment by murlakatamenka** [comment]
@zee-mzha you can remove your comments, I believe. Let's do it together? You first! ;)

**Comment by zee-mzha** [comment]
i uh, what? I'm not sure what you're talking about @murlakatamenka

**Comment by murlakatamenka** [comment]
Ah, my bad. I thought you wrote an comment you didn't mean to. Now I see you occasionally closed the issue.

**Comment by murlakatamenka** [comment]
I'll remove my comments since they don't benefit the thread.

**Comment by Scrumplex** [comment]
Repology is linked on the README now ^^
